# ========================
# ZMK BASIC CONFIG
# ========================

CONFIG_ZMK_KEYBOARD_NAME="MyKeyboard"

# ========================
# BLUETOOTH (IMPORTANT)
# ========================
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y
CONFIG_ZMK_BLE=y
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="ZMK Keyboard"

# Increase connection stability
CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=5

# ========================
# POWER / BATTERY
# ========================

CONFIG_ZMK_BATTERY_REPORTING=y

# ========================
# USB (OPTIONAL BUT USEFUL)
# ========================

CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_HID=y

# ========================
# DEBOUNCE / TYPING FEEL
# ========================

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# ========================
# LOGGING (FOR DEBUG)
# ========================
CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_USB_CDC_ACM=y
CONFIG_SERIAL=y





CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
